// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentPL.Data;

#nullable disable

namespace StudentPL.Migrations
{
    [DbContext(typeof(StudentPLContext))]
    partial class StudentPLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentPL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Algebra")
                        .HasColumnType("int");

                    b.Property<int>("Astronomy")
                        .HasColumnType("int");

                    b.Property<int>("Biology")
                        .HasColumnType("int");

                    b.Property<int>("Chemistry")
                        .HasColumnType("int");

                    b.Property<int>("ComputerScience")
                        .HasColumnType("int");

                    b.Property<int>("Economy")
                        .HasColumnType("int");

                    b.Property<int>("ForeignLanguage")
                        .HasColumnType("int");

                    b.Property<int>("Geography")
                        .HasColumnType("int");

                    b.Property<int>("Geometry")
                        .HasColumnType("int");

                    b.Property<int>("LifeSafetyFundamentals")
                        .HasColumnType("int");

                    b.Property<int>("Literature")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicalCulture")
                        .HasColumnType("int");

                    b.Property<int>("Physics")
                        .HasColumnType("int");

                    b.Property<int>("RussianLanguage")
                        .HasColumnType("int");

                    b.Property<int>("SocialScience")
                        .HasColumnType("int");

                    b.Property<int>("Story")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
